name: CICD

on:
  push:
    branches: [cicd-docker-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t midzy0526/test .
      - name: Publish image to docker hub
        run: docker push midzy0526/test:latest

  deploy:
    needs: build
    runs-on: []
